### ISSUE TITLE
Dynamic `Breaking` value

### ISSUE THREAD

**Issue by xuorig** [xuorig/graphql-schema_comparator#1]
Some types of change are breaking in certain cases, and sometimes not. Using the info we have, can we determine if the change is breaking?

**Comment by rmosolgo** [comment]
>  breaking in certain cases

just curious, what's an example of that?

**Comment by xuorig** [comment]
For example:

Adding an input field is not really breaking when the field is nullable. But definitely breaking when that input field is non-null.

**Comment by rmosolgo** [comment]
Oh, I see, I guess I always thought of them as two _separate_ cases, like:

- Adding an optional argument or input field is not a breaking change 
- Adding a required argument or input field is a breaking change

I thought this issue might have been about application-related breaking changes. For example, we've been considering changes like: "field _x_ returns interface _y_, it used to return object _z_ (part of interface _y_), but we're going to switch it to return object _q_ in some cases (also part of interface _y_)." So it's not breaking from GraphQL's perspective, but it could break client code, because the API response doesn't match their expectations. Another problem, I suppose!

**Comment by xuorig** [comment]
Good point! These ones are tricky also 🤔
